name: Github Pages Deploy

on:
  push:
    branches:
      - "master"
jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [15.x]

    steps:
      - name: Checkout
        uses: NamTranQuoc/test@master

      - name: Install and build
        run: npm install && npm run build

      - name: Deploy
        uses: NamTranQuoc/test
        with:
          branch: master
          folder: build
